// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/daichi1002/go-graphql/adapters/repositories"
	"github.com/daichi1002/go-graphql/usecases"
	"github.com/daichi1002/go-graphql/usecases/user"
)

// Injectors from wire.go:

func initGetUser() usecases.GetUserUsecase {
	userRepository := repositories.NewUserRepository()
	getUserUsecase := user.NewGetUserInteractor(userRepository)
	return getUserUsecase
}
