package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/daichi1002/go-graphql/adapters/graph/generated"
	"github.com/daichi1002/go-graphql/di"
	"github.com/daichi1002/go-graphql/entities"
	"github.com/daichi1002/go-graphql/entities/model"
	"github.com/daichi1002/go-graphql/util"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, createUserInfo model.CreateUserInfo) (bool, error) {
	err := entities.Validate(createUserInfo)

	if err != nil {
		return false, err
	}

	err = di.Provide().CreateUser.Handle(ctx, createUserInfo)

	if err != nil {
		return false, err
	}

	return true, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, updateUserInfo model.UpdateUserInfo) (bool, error) {
	err := entities.Validate(updateUserInfo)

	if err != nil {
		return false, err
	}

	err = di.Provide().UpdateUser.Handle(ctx, updateUserInfo)

	if err != nil {
		return false, err
	}

	return true, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, userID string) (bool, error) {
	err := di.Provide().DeleteUser.Handle(ctx, userID)

	if err != nil {
		return false, err
	}

	return true, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	result, err := di.Provide().GetUsers.Handle(ctx)

	if err != nil {
		return nil, util.NewGqlError(ctx, err, entities.UNEXPECTED)
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, userID string) (*model.User, error) {
	result, err := di.Provide().GetUser.Handle(ctx, userID)

	if err != nil {
		return nil, util.NewGqlError(ctx, err, entities.UNEXPECTED)
	}

	return result, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
